# Generated by Django 3.0.3 on 2020-02-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padre_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualization',
            name='title',
            field=models.CharField(default='', max_length=150),
        ),
    ]
