# Generated by Django 3.0.3 on 2020-02-20 16:37

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('padre_data', '0003_auto_20200217_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualization',
            name='data',
            field=jsonfield.fields.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='visualization',
            name='visualization',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
