# Generated by Django 3.0.3 on 2020-02-22 17:23

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('padre_data', '0004_auto_20200220_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='splitvisualization',
            name='pr_curve_data',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
