# Generated by Django 3.0.3 on 2020-03-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padre_data', '0005_splitvisualization_pr_curve_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='splitvisualization',
            name='multi_class',
            field=models.BooleanField(default=False),
        ),
    ]
