# Generated by Django 3.0.3 on 2020-04-09 08:49

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('padre_data', '0006_splitvisualization_multi_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='runvisualization',
            name='multi_class',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='runvisualization',
            name='pr_curve_data',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
